In [ ]:
#FAKE NEWS DETECTION
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import re
import string

In [ ]:
df_fake=pd.read_csv("fake.csv")
df_true=pd.read_csv("true.csv")

In [ ]:
df_fake.head()

                                               title  ...               date
0   Donald Trump Sends Out Embarrassing New Year’...  ...  December 31, 2017
1   Drunk Bragging Trump Staffer Started Russian ...  ...  December 31, 2017
2   Sheriff David Clarke Becomes An Internet Joke...  ...  December 30, 2017
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...  December 29, 2017
4   Pope Francis Just Called Out Donald Trump Dur...  ...  December 25, 2017

[5 rows x 4 columns]

In [ ]:
df_true.head()

                                               title  ...                date
0  As U.S. budget fight looms, Republicans flip t...  ...  December 31, 2017
1  U.S. military to accept transgender recruits o...  ...  December 29, 2017
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...  December 31, 2017
3  FBI Russia probe helped by Australian diplomat...  ...  December 30, 2017
4  Trump wants Postal Service to charge 'much mor...  ...  December 29, 2017

[5 rows x 4 columns]

In [ ]:
df_fake.shape,df_true.shape

((23481, 4), (21417, 4))

In [ ]:
df_fake["class"]=0
df_true["class"]=1

In [ ]:
df_fake_manual_testing=df_fake.tail(10)
df_fake=df_fake.iloc[:-10]
df_true_manual_testing=df_true.tail(10)
df_true=df_true.iloc[:-10]

In [ ]:
df_fake_manual_testing=pd.concat([df_fake_manual_testing,df_true_manual_testing],axis=0)
df_fake_manual_testing.to_csv("manual_testing.csv")

In [ ]:
df_merge=pd.concat([df_fake,df_true],axis=0)
df_merge.head(10)

                                               title  ... class
0   Donald Trump Sends Out Embarrassing New Year’...  ...     0
1   Drunk Bragging Trump Staffer Started Russian ...  ...     0
2   Sheriff David Clarke Becomes An Internet Joke...  ...     0
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...     0
4   Pope Francis Just Called Out Donald Trump Dur...  ...     0
5   Racist Alabama Cops Brutalize Black Boy While...  ...     0
6   Fresh Off The Golf Course, Trump Lashes Out A...  ...     0
7   Trump Said Some INSANELY Racist Stuff Inside ...  ...     0
8   Former CIA Director Slams Trump Over UN Bully...  ...     0
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...  ...     0

[10 rows x 5 columns]

In [ ]:
df=df_merge.drop(["title","subject","date"],axis=1)
df.head(10)

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0
5  The number of cases of cops brutalizing and ki...      0
6  Donald Trump spent a good portion of his day a...      0
7  In the wake of yet another court decision that...      0
8  Many people have raised the alarm regarding th...      0
9  Just when you might have thought we d get a br...      0

In [ ]:
df=df.sample(frac=1)
df.head(10)

                                                    text  class
5931   Friday was Sasha Obama s 15th birthday. All ar...      0
1342   It was the cringe-inducing handshake seen   an...      0
18887  DUBAI/PARIS (Reuters) - Saudi Arabia s decisio...      1
17221  MOGADISHU (Reuters) - Medics who rushed to hel...      1
5800   A racist Trump supporter who couldn t hack it ...      0
12173  WASHINGTON (Reuters) - North Korea s ambassado...      1
7301   NEW YORK/WASHINGTON (Reuters) - Hillary Clinto...      1
16499  VIENNA (Reuters) - The head of the United Nati...      1
535    WASHINGTON (Reuters) - U.S. Representative Joh...      1
13128  SYDNEY (Reuters) - Australia, concerned about ...      1

In [ ]:
df.isnull().sum()

text     0
class    0
dtype: int64

In [ ]:
def word_drop(text):
  text=text.lower()
  text=re.sub(r'\[.*?\]','',text)
  text=re.sub(r"\W"," ",text)
  text=re.sub(r'https?://\S+|www\.\S+', '', text)
  text=re.sub(r'<.*?>+','',text)
  text=re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
  text=re.sub(r'\n', '', text)
  text=re.sub(r'\w*\d\w*', '', text)
  return text

In [ ]:
df["text"]=df["text"].apply(word_drop)

In [ ]:
df.head(10)

                                                    text  class
5931   friday was sasha obama s  birthday  all around...      0
1342   it was the cringe inducing handshake seen   an...      0
18887  dubai paris  reuters    saudi arabia s decisio...      1
17221  mogadishu  reuters    medics who rushed to hel...      1
5800   a racist trump supporter who couldn t hack it ...      0
12173  washington  reuters    north korea s ambassado...      1
7301   new york washington  reuters    hillary clinto...      1
16499  vienna  reuters    the head of the united nati...      1
535    washington  reuters    u s  representative joh...      1
13128  sydney  reuters    australia  concerned about ...      1

In [ ]:
x=df["text"]
y=df["class"]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorization=TfidfVectorizer()
xv_train=vectorization.fit_transform(x_train)
xv_test=vectorization.transform(x_test)

In [ ]:
#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [ ]:
LR.score(xv_test,y_test)

0.987338386090058

In [ ]:
pred_LR=LR.predict(xv_test)
print(classification_report(y_test,pred_LR))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5827
           1       0.98      0.99      0.99      5388

    accuracy                           0.99     11215
   macro avg       0.99      0.99      0.99     11215
weighted avg       0.99      0.99      0.99     11215

In [ ]:
#Decision Tree Classification
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier()
DT.fit(xv_train,y_train)

DecisionTreeClassifier()

In [ ]:
DT.score(xv_test,y_test)

0.9955416852429781

In [ ]:
pred_DT=DT.predict(xv_test)
print(classification_report(y_test,pred_DT))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5827
           1       1.00      0.99      1.00      5388

    accuracy                           1.00     11215
   macro avg       1.00      1.00      1.00     11215
weighted avg       1.00      1.00      1.00     11215

In [ ]:
#RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestClassifier
RFC=RandomForestClassifier(random_state=0)
RFC.fit(xv_train,y_train)

RandomForestClassifier(random_state=0)

In [ ]:
RFC.score(xv_test,y_test)

0.9913508693713776

In [ ]:
 pred_RFC=RFC.predict(xv_test)
 print(classification_report(y_test,pred_RFC))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5827
           1       0.99      0.99      0.99      5388

    accuracy                           0.99     11215
   macro avg       0.99      0.99      0.99     11215
weighted avg       0.99      0.99      0.99     11215

In [ ]:
news="KILLED: Rancher and protest spokesman Robert  Lavoy  Finicum (Image Source: RT International)21st Century Wire says New eye witness testimony indicates that the FBI and other federal agencies were never fired"
manual_testing(news)

LR prediction: Fake News
DT prediction: Fake News
RFC prediction: Fake News

In [ ]:
#MANUAL TESTING
def output_lable(n):
  if n==0:
    return "Fake News"
  elif n==1:
    return "Not A Fake News"
def manual_testing(news):
  testing_news={"text":[news]}
  new_def_test=pd.DataFrame(testing_news)
  new_def_test["text"]=new_def_test["text"].apply(word_drop)
  new_x_test=new_def_test["text"]
  new_xv_test=vectorization.transform(new_x_test)
  pred_LR=LR.predict(new_xv_test)
  pred_DT=DT.predict(new_xv_test)
  pred_RFC=RFC.predict(new_xv_test)
  return print("\n\nLR prediction: {} \nDT prediction: {} \nRFC prediction: {}".format(output_lable(pred_LR[0]),output_lable(pred_DT[0]),output_lable(pred_RFC[0])))

In [ ]:
news="Patrick Henningsen 21st Century Wire UPDATE: 1-30-2016 Last night, the standoff at Malheur National Wildlife Refuge outside Burns, Oregon took a rather ugly turn which resulted in one man shot dead and another wounded by federal agents.The latest incident took place as two vehicles carrying protesters, led by Ammon Bundy, were en route to a community meeting in the nearby town of John Day in Oregon.According to numerous mainstream media reports and local media outlet Oregon Live,  federal sources  are telling the media that only  3 shots were fired , but a new eye witness testimony by one of the vehicle s passengers tells a very different story.While the mainstream media is still referring to the event as  a shoot-out , according to this latest eye witness account at the scene   no shots were fired by vehicle passengers.According to eyewitness Victoria Sharp, 18 yrs old, from Kansas, who was a passenger in the same truck driven by Arizona rancher Robert  Lavoy  Finicum, along with Ryan Bundy, Ryan Payne and Shawna Cox   dozens of federal vehicles and countless agents were waiting for the group, pre-positioned at a point along the isolated rural Highway 395, before intercepting the group and detaining 8 persons, including brothers Ammon and Ryan Bundy, who were booked into Multnomah County Jail early this morning.Sharp confirmed that the passengers never drew weapons and attempted to get out of their vehicles before federal agents fired  at least 120 shots altogether  at the vehicle carrying her party.RELATED:  Federal Government Escalated the Violence in Oregon Federal agents fired their first shots at passenger and militia leader, Ryan Payne, as he attempted to make contact with the agents by sticking his head and hands out of the window, at which point Payne got back inside the vehicle.Payne then exited the truck and was detained before driver Finicum advanced the vehicle further down the road before sliding into a snow bank on the side of the road.A second vehicle, a Jeep with passengers including Ammon Bundy, had already been stopped by authorities, with its all passengers taken into custody with no one harmed.A third vehicle driving approximately one mile ahead at the front of the convoy, carrying Sharp s mother and young siblings, was allowed to pass through the police roadblocks without incident. Finicum then attempted to drive around the next federal road block, but lost control of the vehicle before careening into snow piled on the road s hard shoulder.After crashing into the snow bank on the side of the highway, the driver, 54 yr old Arizona resident, Lavoy Finicum (photo, above), then exited the vehicle, visibly upset and with his hands in the air, before being gunned down by federal agents. Finicum was walking with his hands in the air, daring federal agents,  Just shoot me! Just shoot me    at which point the agents shot him dead. The witness testimony indicates that his hands were still in the air.Numerous  red dots  from lasers could be seen pointed on the passengers by federal marksmen, in what was described by this witness as an  ambush  by federal authorities. Sharps said,  I had 20 lasers on me when I got out of the car. She also confirmed that Ryan Bundy was shot and wounded in the arm by federal agents was shot while still inside the truck.Federal forces then followed-up by firing CS tear gas rounds around the vehicle, apparently in an attempt to further disable the remaining passengers.At least 40 federal vehicles, as well as many armed federal agents including some seen emerging from the surrounding forest along the highway, should leave little doubt as to the scale and nature of the operation.Listen to Ms. Sharp s harrowing testimony here: IMPORTANT NOTE (UPDATE 1-30-16): According to this recent report by Pedro Quintana from Central Oregon local affiliate News Channel 21, Sheriff Palmer was not at the federal roadblock and had no prior knowledge of the FBI ambush of the Bundy convoy. According to the chat session relayed in Pedro Quintana s report, Palmer was asked in an online chat,  Did you witness Lavoy shooting, or no? , to which Palmer replies,  NO  The shooting from what I hear was close to 4 and I heard of it at about 5:45pm.  News 21continued: Palmer responded he had no knowledge of anything about the plans or who was coming to the public meeting. He went on to say that the  FBI and Oregon State Police know me, they shared nothing with me and they know I wouldn t have allowed it. Earlier mainstream media reports that Palmer was present at the FBI roadblock would lead Bundy supporters to believe that Palmer had betrayed the Bundys and Lavoy Finicum. One the main sources, if not the main source of the original Sheriff Palmer controversy appears to be none other than Oregon Live staff writer Les Zaitz who has slipped-in this key piece of line into his report which which says: They said they didn t know how long the roadblock would be place. Grant County Sheriff Glenn Palmer was there.  Not surprisingly, this has set-off a virtual backlash online against the Grant County Sheriff, as evidenced by the following screen shot of Google search link found here:  Is this a case of media dirty tricks by Oregon Live? Certainly, Oregon Live s coverage of Burns events has been skewed from the beginning, and have been running character assassination pieces against Malheur occupiers in a effort to discredit the protest. Sheriff Palmer is clearly on record as being sympathetic to the Hammond Ranch protest and had recently opened up a constructive dialogue with the Bundys and occupiers from Malheur Wildlife Refuge. If Pedro Quintana s News 21 report is indeed accurate, then one might conclude that Oregon Live put out a piece of disinformation, likely designed to further divide the protest movement and create dissension in militia and activist ranks. However, until Sheriff Glenn Palmer comes out and issues clear statement declaring where he was   and where he wasn t, then people will continue to speculate what really happened. (END OF UPDATE)Conflicting AccountsReporter Les Zaitz from Oregon Live, a key source of mainstream media information from the Refuge protest, did not give prominence to Victoria Sharp s account in his article, but instead chose to lead with and highlight the secondhand account of the other vehicle s passenger Mark McConnell who claimed that unarmed victim Lavoy Finicum  charged at law enforcement  before being shot. Zaitz s article even admits that McConnell s vehicle was at least 200 yards behind the truck driven by Finicum.Incredibly, Oregonian Zaitz appears to favor McConnell s account on the basis that his account has  matched accounts from law enforcement sources.  McConnell issued his version of events after being released from law enforcement custody, where he spoke for 2 hours with federal agents.Tabloid news site Raw Story also ran with a similar narrative with a deceptive headline that read  Eyewitnesses knock down conspiracy theories about LaVoy Finicum , referring to secondhand accounts by McConnell and colleague, Melvin Lee.As it turns out, Mark McConnell did not actually see the shooting, and instead had  pieced together  his account, as evidenced by his own statement later posted online: going off of what Shawna Cox and Ryan Payne were saying, which were in the vehicle, um, Visually, I seen the truck take off, you know, now any time someone takes off in a vehicle away from law enforcement after they exercise a stop, it s typically considered an act of aggression and foolish. Payne said while they were sitting there and they were clearing my vehicle that him and LeVoy had a heated discussion but he took off they had to chase him, and from what Shawna Cox was saying  from inside of his truck that when he exited the vehicle  he charged after law enforcement . What I do know to be true, from what Payne said and what Shawna said taken pieces here and pieces there and from what I witnessed, um, I didn t see the shooting, um, he was not on his knees, he was not, none of that non sense, that was a miscommunication on somebody else s part but he went after em, he charged em. Here, McConnell is, in effect, issuing a proxy statement on behalf of Victoria Sharp s fellow passengers, Shawn Cox and Ryan Payne. This is hardly admissible, as both Cox and Payne are currently in federal custody and are not able to verify the accuracy of McConnell reiteration. And yet, mainstream media outlets are propping-up McConnell s account, while minimizing Sharp s.After speculating about the shooting, McConnell then says,   I didn t see it, and I m not going to speculate on it. McConnell is said to have been driving in the rear vehicle with Ammon Bundy and his private security, Brian Cavalier.SEE ALSO: Activists or Terrorist? The Truth About the Oregon StandoffUPDATE 1-28-2016: On Wednesday evening, CNN International released a report based on an  anonymous government source  claiming that Finicum was killed by federal agents because he was  reaching towards his waistband.  The Washington Post then re-spun the story, and rather incredibly   is relying on the very same secondhand story presented by Mark McConnell, in a desperate attempt to prop-up the government s version of events: In the moments before he was shot by authorities Tuesday afternoon, Finicum led a high-speed getaway attempt. He then reached for his waistband, prompting authorities to open fire, according to a CNN report.The report, which cites anonymous law enforcement officials but has not been confirmed by The Washington Post, is corroborated by a statement from an occupier who said he was traveling with Finicum at the time of the traffic stop. The fact the media have chosen to label this incident as a  traffic stop  indicates an obvious agenda designed to minimize the obvious   that this was a pre-planned, elaborate ambush by the FBI and Oregon State Police.This same unnamed  source  cited by CNN is also told the network that the incident was indeed captured on video by the FBI, but that authorities  have not decided whether or not the release the video.  (see more breaking updates on this development below)See a full breakdown CNN, Washington Post and the government narrative here.Federal EscalationThis shocking turn of events comes just days after Oregon governor Kate Brown issued what some might consider to be a veiled threat to the protesters and militia, saying that the federal government  must move quickly to end the occupation and hold all of the wrongdoers accountable. Reports last week indicated that the governor had personally written the White House and President Obama, which specifically addressed Attorney General Loretta Lynch and FBI director James Comey, in which Brown expressed her outrage that Harney County and the state of Oregon was not being recognized for its  collaborative achievements , but rather for  outsiders seeking to exploit and manipulate a local matter for their own agenda. According to the FBI s press release, arrested individuals include:Ammon Edward Bundy, 40, of Emmett, Idaho Ryan C. Bundy, 43, of Bunkerville, Nevada Brian Cavalier, 44, of Bunkerville, Nevada Shawna Cox, 59, of Kanab, Utah Ryan Waylen Payne, 32, of Anaconda, Montana Joseph Donald O Shaughnessy, 45, of Cottonwood, ArizonaAfter the federal operation on Highway 395, in a separate incident back at the Wildlife Refuge, YouTube and internet radio personality, Peter Santilli, 50, of Cincinnati, Ohio, approached the venue and walked towards federal agents before being taken into custody.BREAKING: Booking photos of Ammon Bundy, 7 others after arrest near Burns. https://t.co/AcqRyP4pd5 #KOIN6News pic.twitter.com/un82wepf95  Brent Weisberg (@BrentKOIN) January 27, 2016Those still in detention are scheduled to be arraigned at 1:30 p.m. Tuesday in U.S. District Court in Portland.According to reports, FBI agents in Phoenix also  made a probable cause arrest of Jon Eric Ritzheimer, age 32, on a federal charge related to the armed occupation of the Malheur National Wildlife Refuge in Harney County, Oregon. Jon Ritzheimer, another controversial YouTube personality and former US Marine, appears to have left the Malheur Refuge right before the federal operation to apprehend the protesters, when he returned to his home in Peoria, Arizona.Back at the Refuge protest site, the FBI are said to be negotiating with remaining 8 to 10 occupiers inside, with reports that most women and minors have already left the site.Three weeks ago, Finicum, who become the protest s media spokesperson, made a prophetic statement on camera saying that,  There are things more important than your life, and freedom is one of them.  Watch:UPDATE 1-28-2016: Any public distrust or skepticism of the federal authorities would immediately be dispelled by speed release of all video footage (with dozens of agents and surveillance, there should have been more than one video feed taken, including body and gun sight cameras) of the event. Whether or not, and how fast this will happen remains to be seen.UPDATE 1-29-2016 at 01:30PM ET: Due to public pressure and intense speculation about the events of Tuesday evening, and also because of the YouTube recording of eye witness 18 yr old Victoria Sharp, the FBI has released the unedited aerial video footage from Tuesday evening s incident which took place along Highway 395 here. According to the official FBI statement:  We feel that it is necessary to show the whole thing unedited in the interest of transparency.  The FBI video entitled,  Complete, Unedited Video of Joint FBI and OSP Operation 01/26/2016 , does show the victim Lavoy Finicum exiting the truck awkwardly in at least two feet of snow, and he clearly does not  charge towards  the SWAT team, and his hands are clearly held high above his head as he exits his truck when confronted by a SWAT team, before being shot multiple times by marksmen and falling in the snow. Also, the scale and size of this operation is very evident by the footage, and the apprehension of the protesters was not the result of a mere  traffic stop  as erroneously characterized in multiple mainstream media reports. On its own, this FBI drone footage would appear to support previous government and media claims by CNN, Washington Post and others that the victim was indeed  reaching towards his waistband  which gave federal and state police justification to unleash deadly force. However, it is still not completely clear from this aerial footage whether or not Finicum was holstered (he is said to normally carry a gun on the right hip, but FBI are claiming he had a 9mm gun in his inside left breast pocket), but also whether or not he lowered his arms before, or after he was shot multiple times. For example, if Finicum had his hands in the air and was then was shot in the abdomen first, then any man s natural reaction would be to then lower his hand(s) and clutch the wound. Additionally, if any shots were fired, even in the vicinity, then confusion could have ensued which might have prompted Finicum to reach for his weapon. Either way, it is impossible to make any such a forensic determination without a corresponding audio track  which would help to determine if any shots were fired before Finicum s hand(s) could be seen lowering. WARNING: Images depict violence which some viewers may find disturbing. Watch here: READ MORE OREGON STANDOFF NEWS AT: 21st Century Wire Oregon Standoff Files"
manual_testing(news)

LR prediction: Fake News
DT prediction: Fake News
RFC prediction: Fake News

In [ ]:
news="LONDON (Reuters) - Abdul Daoud spilt most of the cappuccino into the saucer the first time he served Princess Diana, his nerves getting the better of him. Almost 20 years on since she was killed when her car crashed in a Paris tunnel, he still works surrounded by pictures of the woman he calls  the princess of the people  in his cafe, named Diana, his very personal attempt to keep her memory alive.  My promise to her is to put this place as a tribute for her,  he said of his cafe, set up in 1989, near London s Kensington Gardens, home to the palace where Diana used to live.  For him, celebrating her life is  business as usual  at the cafe where visitors can eat Diana salads or Diana burgers and where he said she used to stop by regularly.   She is the princess of the people, always,  he said, adding that he does not believe she will ever be forgotten. But many younger Britons said that while they can understand the fascination with the princess, whose struggles to fit in to the royal household played out in the full glare of the media, they don t feel it themselves.       I think she maybe meant more to my mother,  said Stephen Butler in the west London area Diana used to live.  When she died I remember my mother shaking me awake and being quite devastated about it.  Student Shermine Grigorius was three-years-old when Diana died but after being told stories about the Princess of Wales by her mother, sees her as a  symbol of kindness .  While the royals have always been dutifully charitable, Diana was known for going beyond her in-laws, or even any celebrity at the time, in her philanthropy.  Whether in charity work or in royal life, she earned a reputation for being a rebel who defied convention: from campaigning for a worldwide ban on landmines despite opposition from the British government to flouting royal protocol to speak candidly about her experiences with bulimia and infidelity.   She bought a different side to the whole monarchy,  said Anika Wijuria, a 30-year-old project manager.  They were quite stiff and she was quite liberal.  At the Da Mario restaurant, Marco Molino remembers another side of Diana, describing a  down to earth  woman who liked to eat Italian dishes with her sons, Princes William and Harry, or friends.  Her personality was very normal, very down to earth, very friendly,  he said near an oil painting of Diana on the wall.  I think that s what she really wanted - a bit of normality ... Here was one of the places where she could achieve that.  Ronald van Bronkhorst, who has lived above Da Mario since the 70s, also said she never made flashy entrances.  Her legacy will never leave ... You think about her all the time, especially in the area we live in.  "
manual_testing(news)

LR prediction: Not A Fake News
DT prediction: Not A Fake News
RFC prediction: Not A Fake News